name: manual-deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "enter your environment"
        required: true
        default: "staging"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print environment
        run: echo "Environment = $ {{ github.event.inputs.environment }}
